version: 1.0.{build}
image:
- Visual Studio 2017
test: off
build:
  parallel: true
platform:
- x64
environment:
  matrix:
  - CPP: latest
    CONFIG: Release
    SHARED: ON
build_script:
- cd open3d-type
- ./build.sh
