version: 1.0.{build}
image:
- Visual Studio 2017
test: off
build:
  parallel: true
platform:
- x64
environment:
  matrix:
  - CPP: latest
    CONFIG: Release
    SHARED: ON
install:
- ps: |
  $env:CMAKE_ARCH = "x64"
  $env:CMAKE_GENERATOR = "Visual Studio 15 2017"
build_script:
- cd open3d-type
- mkdir -p build
- cd build
- cmake -G "%CMAKE_GENERATOR%" -A "%CMAKE_ARCH%" ..
- cmake --build . --parallel %NUMBER_OF_PROCESSORS% --config %CONFIG%
