version: 1.0.{build}
image:
- Visual Studio 2017
test: off
build:
  parallel: true
platform:
- x64
environment:
  matrix:
  - CPP: latest
    CONFIG: Release
build_script:
- cd open3d-type
- mkdir -p build
- cd build
- cmake -G "Visual Studio 15 2017" -A "x64" ..
- cmake --build . --parallel %NUMBER_OF_PROCESSORS% --config %CONFIG%
